# -------- Build stage --------
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY PMS.csproj ./
COPY . .

RUN dotnet restore PMS.csproj

RUN dotnet build PMS.csproj -c Release

RUN dotnet publish PMS.csproj -c Release -o /app/publish

# -------- Runtime stage --------
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app

ENV ASPNETCORE_URLS=http://+:4004

COPY --from=build /app/publish .

EXPOSE 4004

ENTRYPOINT ["dotnet", "PMS.dll"]